spring:
  application:
    name: "accounts"

build:
  version: "4.0 (Git-DEV)"

info:
  app:
    name: ${spring.application.name}
    description: "Waffle Bank Accounts Service"
    version: ${build.version}